#!/bin/sh

set -e

installed_docker_version="$(docker version -f "{{.Client.Version}}")"
uname_result="$(uname)"

require_docker () {
  local required_docker_version="$1"
  if ! printf "$required_docker_version\n$installed_docker_version\n" | sort -cnt . -k 1,1 -k 2,2 -k 3,3 2>/dev/null; then
    echo "This script requires Docker version $required_docker_version or newer, but your installed version" >&2
    echo "is $installed_docker_version. Please upgrade your Docker installation!" >&2
    echo >&2
    echo 'Note that on Windows / OS X you need to install **Docker Toolbox**, (NOT Docker' >&2
    echo 'for Windows or Docker for Mac).' >&2
    echo >&2
    exit 1
  fi

  if [ "$uname_result" != Linux ] && [ -z "${DOCKER_MACHINE_NAME:-}" ]; then
    echo 'You seem to be using a non-Linux platform, but your shell is not configured to' >&2
    echo 'connect to a Docker Machine. Please configure your shell with the following' >&2
    echo 'command:' >&2
    echo >&2
    echo '    eval "$(docker-machine env default)"' >&2
    echo >&2
    echo 'If the machine named "default" does not exists, follow the instructions on this' >&2
    echo 'page to create it:' >&2
    echo >&2
    echo '    https://docs.docker.com/machine/get-started/#create-a-machine' >&2
    echo >&2
    exit 1
  fi
}

if [ -z "${TEST+1}" ]; then
  require_docker '1.11.1'
  if [ -n "${DOCKER_MACHINE_NAME+1}" ]; then
    echo "Docker Machine detected, copying the script over to machine '$DOCKER_MACHINE_NAME' and running there."
    docker-machine scp "$0" "$DOCKER_MACHINE_NAME:/tmp/systemd-container-host-config"
    docker-machine ssh "$DOCKER_MACHINE_NAME" 'chmod a+x /tmp/systemd-container-host-config && /tmp/systemd-container-host-config'
  else
    if mount | grep /sys/fs/cgroup/systemd >/dev/null 2>&1; then
      echo 'The systemd cgroup is already mounted at /sys/fs/cgroup/systemd.'
    else
      if [ -d /sys/fs/cgroup/systemd ]; then
        echo 'The mount point for the systemd cgroup already exists at /sys/fs/cgroup/systemd.'
      else
        echo 'Creating the mount point for the systemd cgroup at /sys/fs/cgroup/systemd.'
        sudo mkdir -p /sys/fs/cgroup/systemd
      fi

      echo 'Mounting the systemd cgroup.'
      sudo mount -t cgroup cgroup -o none,name=systemd /sys/fs/cgroup/systemd
    fi

    if uname -r | grep boot2docker >/dev/null 2>&1; then
      echo 'boot2docker detected.'
      if grep systemd-container-host-config /var/lib/boot2docker/bootlocal.sh >/dev/null 2>&1; then
        echo 'systemd-container-host-config already added to /var/lib/boot2docker/bootlocal.sh'
      else
        echo 'Adding systemd-container-host-config to /var/lib/boot2docker/bootlocal.sh'
        sudo cp /tmp/systemd-container-host-config /var/lib/boot2docker/
        echo /var/lib/boot2docker/systemd-container-host-config | sudo tee -a /var/lib/boot2docker/bootlocal.sh >/dev/null
      fi
    fi
    echo 'Your Docker host is now configured for running systemd containers!'
  fi
fi
